package org.zero.boot.dao.first.entity;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.age
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.gendar
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    private String gendar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.age
     *
     * @return the value of person.age
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.age
     *
     * @param age the value for person.age
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.gendar
     *
     * @return the value of person.gendar
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    public String getGendar() {
        return gendar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.gendar
     *
     * @param gendar the value for person.gendar
     *
     * @mbg.generated Fri Nov 03 15:08:19 CST 2017
     */
    public void setGendar(String gendar) {
        this.gendar = gendar == null ? null : gendar.trim();
    }
}