package org.zero.boot.dao.first.entity;

import java.util.Date;

public class SysMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String menucode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menuName
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menuPath
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String menupath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.parentMenuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String parentmenucode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.status
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.updateUser
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String updateuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.updateTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menuCode
     *
     * @return the value of sys_menu.menuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menuCode
     *
     * @param menucode the value for sys_menu.menuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menuName
     *
     * @return the value of sys_menu.menuName
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menuName
     *
     * @param menuname the value for sys_menu.menuName
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menuPath
     *
     * @return the value of sys_menu.menuPath
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getMenupath() {
        return menupath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menuPath
     *
     * @param menupath the value for sys_menu.menuPath
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setMenupath(String menupath) {
        this.menupath = menupath == null ? null : menupath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.parentMenuCode
     *
     * @return the value of sys_menu.parentMenuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getParentmenucode() {
        return parentmenucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.parentMenuCode
     *
     * @param parentmenucode the value for sys_menu.parentMenuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setParentmenucode(String parentmenucode) {
        this.parentmenucode = parentmenucode == null ? null : parentmenucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.status
     *
     * @return the value of sys_menu.status
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.status
     *
     * @param status the value for sys_menu.status
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.creator
     *
     * @return the value of sys_menu.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.creator
     *
     * @param creator the value for sys_menu.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.createTime
     *
     * @return the value of sys_menu.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.createTime
     *
     * @param createtime the value for sys_menu.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.updateUser
     *
     * @return the value of sys_menu.updateUser
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.updateUser
     *
     * @param updateuser the value for sys_menu.updateUser
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.updateTime
     *
     * @return the value of sys_menu.updateTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.updateTime
     *
     * @param updatetime the value for sys_menu.updateTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}