package org.zero.boot.dao.first.entity;

import java.util.Date;

public class SysRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roleCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String rolecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.roleName
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.status
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.updateUser
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String updateuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.updateTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.id
     *
     * @return the value of sys_role.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.id
     *
     * @param id the value for sys_role.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roleCode
     *
     * @return the value of sys_role.roleCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roleCode
     *
     * @param rolecode the value for sys_role.roleCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.roleName
     *
     * @return the value of sys_role.roleName
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.roleName
     *
     * @param rolename the value for sys_role.roleName
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.status
     *
     * @return the value of sys_role.status
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.status
     *
     * @param status the value for sys_role.status
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.creator
     *
     * @return the value of sys_role.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.creator
     *
     * @param creator the value for sys_role.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.createTime
     *
     * @return the value of sys_role.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.createTime
     *
     * @param createtime the value for sys_role.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.updateUser
     *
     * @return the value of sys_role.updateUser
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.updateUser
     *
     * @param updateuser the value for sys_role.updateUser
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.updateTime
     *
     * @return the value of sys_role.updateTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.updateTime
     *
     * @param updatetime the value for sys_role.updateTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}