package org.zero.boot.dao.first.entity;

import java.util.Date;

public class SysRoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.roleCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String rolecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.menuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String menucode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.id
     *
     * @return the value of sys_role_menu.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.id
     *
     * @param id the value for sys_role_menu.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.roleCode
     *
     * @return the value of sys_role_menu.roleCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.roleCode
     *
     * @param rolecode the value for sys_role_menu.roleCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.menuCode
     *
     * @return the value of sys_role_menu.menuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.menuCode
     *
     * @param menucode the value for sys_role_menu.menuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.creator
     *
     * @return the value of sys_role_menu.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.creator
     *
     * @param creator the value for sys_role_menu.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.createTime
     *
     * @return the value of sys_role_menu.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.createTime
     *
     * @param createtime the value for sys_role_menu.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}