package org.zero.boot.dao.first.entity;

import java.util.Date;

public class SysResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.code
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.name
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.path
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.menuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String menucode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.type
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.status
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.updateUser
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String updateuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.updateTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.id
     *
     * @return the value of sys_resource.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.id
     *
     * @param id the value for sys_resource.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.code
     *
     * @return the value of sys_resource.code
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.code
     *
     * @param code the value for sys_resource.code
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.path
     *
     * @return the value of sys_resource.path
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.path
     *
     * @param path the value for sys_resource.path
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.menuCode
     *
     * @return the value of sys_resource.menuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.menuCode
     *
     * @param menucode the value for sys_resource.menuCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.type
     *
     * @return the value of sys_resource.type
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.type
     *
     * @param type the value for sys_resource.type
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.status
     *
     * @return the value of sys_resource.status
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.status
     *
     * @param status the value for sys_resource.status
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.creator
     *
     * @return the value of sys_resource.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.creator
     *
     * @param creator the value for sys_resource.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.createTime
     *
     * @return the value of sys_resource.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.createTime
     *
     * @param createtime the value for sys_resource.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.updateUser
     *
     * @return the value of sys_resource.updateUser
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.updateUser
     *
     * @param updateuser the value for sys_resource.updateUser
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.updateTime
     *
     * @return the value of sys_resource.updateTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.updateTime
     *
     * @param updatetime the value for sys_resource.updateTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}