package org.zero.boot.dao.first.entity;

import java.util.Date;

public class SysUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.username
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.roleCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String rolecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.id
     *
     * @return the value of sys_user_role.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.id
     *
     * @param id the value for sys_user_role.id
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.username
     *
     * @return the value of sys_user_role.username
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.username
     *
     * @param username the value for sys_user_role.username
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.roleCode
     *
     * @return the value of sys_user_role.roleCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.roleCode
     *
     * @param rolecode the value for sys_user_role.roleCode
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.creator
     *
     * @return the value of sys_user_role.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.creator
     *
     * @param creator the value for sys_user_role.creator
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.createTime
     *
     * @return the value of sys_user_role.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.createTime
     *
     * @param createtime the value for sys_user_role.createTime
     *
     * @mbg.generated Thu Dec 28 21:28:47 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}