package org.zero.boot.dao.third.repostory;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zero.boot.dao.third.entity.BbsReply;
import org.zero.boot.dao.third.entity.BbsReplyExample;

public interface BbsReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    long countByExample(BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int deleteByExample(BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int insert(BbsReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int insertSelective(BbsReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    List<BbsReply> selectByExampleWithBLOBs(BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    List<BbsReply> selectByExample(BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    BbsReply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") BbsReply record, @Param("example") BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") BbsReply record, @Param("example") BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int updateByExample(@Param("record") BbsReply record, @Param("example") BbsReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int updateByPrimaryKeySelective(BbsReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(BbsReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bbs_reply
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    int updateByPrimaryKey(BbsReply record);
}