package org.zero.boot.dao.third.entity;

import java.util.Date;

public class BbsReply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.id
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.pid
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.top_pid
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Long topPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.tid
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Long tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.user_id
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.floor
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.likes
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Integer likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.unlikes
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Integer unlikes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.collections
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Integer collections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.create_time
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.update_time
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.status
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bbs_reply.content
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.id
     *
     * @return the value of bbs_reply.id
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.id
     *
     * @param id the value for bbs_reply.id
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.pid
     *
     * @return the value of bbs_reply.pid
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.pid
     *
     * @param pid the value for bbs_reply.pid
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.top_pid
     *
     * @return the value of bbs_reply.top_pid
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Long getTopPid() {
        return topPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.top_pid
     *
     * @param topPid the value for bbs_reply.top_pid
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setTopPid(Long topPid) {
        this.topPid = topPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.tid
     *
     * @return the value of bbs_reply.tid
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.tid
     *
     * @param tid the value for bbs_reply.tid
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.user_id
     *
     * @return the value of bbs_reply.user_id
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.user_id
     *
     * @param userId the value for bbs_reply.user_id
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.floor
     *
     * @return the value of bbs_reply.floor
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.floor
     *
     * @param floor the value for bbs_reply.floor
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.likes
     *
     * @return the value of bbs_reply.likes
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.likes
     *
     * @param likes the value for bbs_reply.likes
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.unlikes
     *
     * @return the value of bbs_reply.unlikes
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Integer getUnlikes() {
        return unlikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.unlikes
     *
     * @param unlikes the value for bbs_reply.unlikes
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setUnlikes(Integer unlikes) {
        this.unlikes = unlikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.collections
     *
     * @return the value of bbs_reply.collections
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Integer getCollections() {
        return collections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.collections
     *
     * @param collections the value for bbs_reply.collections
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setCollections(Integer collections) {
        this.collections = collections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.create_time
     *
     * @return the value of bbs_reply.create_time
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.create_time
     *
     * @param createTime the value for bbs_reply.create_time
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.update_time
     *
     * @return the value of bbs_reply.update_time
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.update_time
     *
     * @param updateTime the value for bbs_reply.update_time
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.status
     *
     * @return the value of bbs_reply.status
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.status
     *
     * @param status the value for bbs_reply.status
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bbs_reply.content
     *
     * @return the value of bbs_reply.content
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bbs_reply.content
     *
     * @param content the value for bbs_reply.content
     *
     * @mbg.generated Fri Jun 08 00:47:45 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}