package org.zero.boot.dao.first.repository;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zero.boot.dao.first.entity.AccountRunning;
import org.zero.boot.dao.first.entity.AccountRunningExample;

public interface AccountRunningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    long countByExample(AccountRunningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    int insert(AccountRunning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    int insertSelective(AccountRunning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    List<AccountRunning> selectByExample(AccountRunningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    AccountRunning selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") AccountRunning record, @Param("example") AccountRunningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    int updateByExample(@Param("record") AccountRunning record, @Param("example") AccountRunningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    int updateByPrimaryKeySelective(AccountRunning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_running
     *
     * @mbg.generated Mon Nov 20 22:36:37 CST 2017
     */
    int updateByPrimaryKey(AccountRunning record);
}